# ----------------------------------------------------------------------------------------------------------------------
# General.
# ----------------------------------------------------------------------------------------------------------------------

baseURL = 'https://lib.onl/'
theme = ['ui-shortcodes', 'ui-custom', 'ui-base']
DefaultContentLanguage = 'ru'
defaultContentLanguageInSubdir = true
disableHugoGeneratorInject = true
paginate = 10
enableEmoji = true
enableGitInfo = true
pygmentsUseClasses = true
pygmentsCodeFences = true
publishdir = 'public'
enableRobotsTXT = true
rssLimit = 10

# ----------------------------------------------------------------------------------------------------------------------
# Errors.
# ----------------------------------------------------------------------------------------------------------------------

ignoreErrors = ["error-remote-getjson"]

# ----------------------------------------------------------------------------------------------------------------------
# Outputs.
# ----------------------------------------------------------------------------------------------------------------------

[outputs]
home = ['html', 'rss', 'opensearch', 'manifest']
page = ['html', 'json']

# ----------------------------------------------------------------------------------------------------------------------
# Sitemap.
# ----------------------------------------------------------------------------------------------------------------------

[sitemap]
changefreq = 'weekly'
priority = 0.5

# ----------------------------------------------------------------------------------------------------------------------
# Taxonomies.
# ----------------------------------------------------------------------------------------------------------------------

[taxonomies]
author = 'authors'
tag = 'tags'
category = 'categories'

# ----------------------------------------------------------------------------------------------------------------------
# Social.
# ----------------------------------------------------------------------------------------------------------------------

[social]
twitter = ''

# ----------------------------------------------------------------------------------------------------------------------
# Permalinks.
# ----------------------------------------------------------------------------------------------------------------------

[permalinks]
posts = '/:section/:year/:month/:slug/'

# ----------------------------------------------------------------------------------------------------------------------
# Markup.
# ----------------------------------------------------------------------------------------------------------------------

[markup.tableOfContents]
ordered = false
startLevel = 2
endLevel = 6

[markup.highlight]
codeFences = false

# ----------------------------------------------------------------------------------------------------------------------
# Media Types.
# ----------------------------------------------------------------------------------------------------------------------

[mediaTypes.'application/opensearchdescription+xml']
suffixes = ['xml']

# ----------------------------------------------------------------------------------------------------------------------
# Output Formats.
# ----------------------------------------------------------------------------------------------------------------------

[outputFormats.opensearch]
baseName = 'opensearch'
mediaType = 'application/opensearchdescription+xml'
rel = 'search'

[outputFormats.manifest]
baseName = 'manifest'
mediaType = 'application/json'
rel = 'manifest'

# ----------------------------------------------------------------------------------------------------------------------
# Minify.
# ----------------------------------------------------------------------------------------------------------------------

[minify]
minifyOutput = true

[minify.tdewolff.html]
keepWhitespace = false
