# -------------------------------------------------------------------------------------------------------------------- #
# General.
# -------------------------------------------------------------------------------------------------------------------- #

baseURL: 'https://lib.onl/'
theme:
  - 'ui-shortcode'
  - 'ui-custom'
  - 'ui-blog'
DefaultContentLanguage: 'ru'
defaultContentLanguageInSubdir: 1
disableHugoGeneratorInject: 1
paginate: 10
enableEmoji: 1
pygmentsUseClasses: 1
pygmentsCodeFences: 1
publishDir: 'public'
enableRobotsTXT: 1
rssLimit: 10

# -------------------------------------------------------------------------------------------------------------------- #
# Errors.
# -------------------------------------------------------------------------------------------------------------------- #

ignoreErrors:
  - 'error-remote-getjson'

# -------------------------------------------------------------------------------------------------------------------- #
# Outputs.
# -------------------------------------------------------------------------------------------------------------------- #

outputs:
  home:
    - 'html'
    - 'rss'
  page:
    - 'html'

# -------------------------------------------------------------------------------------------------------------------- #
# Sitemap.
# -------------------------------------------------------------------------------------------------------------------- #

sitemap:
  changefreq: 'weekly'
  priority: 0.5

# -------------------------------------------------------------------------------------------------------------------- #
# Taxonomies.
# -------------------------------------------------------------------------------------------------------------------- #

taxonomies:
  tag: 'tags'
  category: 'categories'
  author: 'authors'

# -------------------------------------------------------------------------------------------------------------------- #
# Permalinks.
# -------------------------------------------------------------------------------------------------------------------- #

permalinks:
  posts: '/:section/:year/:month/:slug/'

# -------------------------------------------------------------------------------------------------------------------- #
# Markup.
# -------------------------------------------------------------------------------------------------------------------- #

markup:
  goldmark:
    parser:
      autoHeadingID: false
  highlight:
    lineNos: true
    noClasses: false

# -------------------------------------------------------------------------------------------------------------------- #
# Minify.
# -------------------------------------------------------------------------------------------------------------------- #

minify:
  minifyOutput: 1
  tdewolff:
    html:
      keepWhitespace: 0

# -------------------------------------------------------------------------------------------------------------------- #
# Languages.
# -------------------------------------------------------------------------------------------------------------------- #

languages:
  ru:
    title: 'Library Online'
    contentDir: 'content/ru'
    languageName: 'Русский'
    languageCode: 'ru-RU'
    weight: 10
    params:
      description: 'Заметки на тему администрирования и разработки различных систем, приложений и серверов.'
      languageLang: 'ru'
  en:
    title: 'Library Online'
    contentDir: 'content/en'
    languageName: 'English'
    languageCode: 'en-US'
    weight: 20
    params:
      description: 'Notes on system administration and development of various systems, applications and servers.'
      languageLang: 'en'
