# -------------------------------------------------------------------------------------------------------------------- #
# General.
# -------------------------------------------------------------------------------------------------------------------- #

baseURL: 'https://lib.onl/'
theme: [ 'ui-shortcode', 'ui-custom', 'ui-blog' ]
DefaultContentLanguage: 'ru'
defaultContentLanguageInSubdir: true
disableHugoGeneratorInject: true
paginate: 20
pygmentsUseClasses: true
pygmentsCodeFences: true
publishDir: 'public'
enableRobotsTXT: true
rssLimit: 50

# -------------------------------------------------------------------------------------------------------------------- #
# Errors.
# -------------------------------------------------------------------------------------------------------------------- #

ignoreErrors:
  - 'error-remote-getjson'

# ----------------------------------------------------------------------------------------------------------------------
# Media Types.
# ----------------------------------------------------------------------------------------------------------------------

mediaTypes:
  'application/opensearchdescription+xml':
    suffixes: [ 'xml' ]

# ----------------------------------------------------------------------------------------------------------------------
# Output Formats.
# ----------------------------------------------------------------------------------------------------------------------

outputFormats:
  openSearch:
    baseName: 'opensearch'
    mediaType: 'application/opensearchdescription+xml'
    rel: 'search'
    notAlternative: true
  manifest:
    baseName: 'manifest'
    mediaType: 'application/json'
    rel: 'manifest'
    notAlternative: true
  search:
    baseName: 'search'
    mediaType: 'application/json'
    isPlainText: true
    notAlternative: true
  turbo:
    baseName: 'turbo'
    mediaType: 'application/rss+xml'
    notAlternative: true

# -------------------------------------------------------------------------------------------------------------------- #
# Outputs.
# -------------------------------------------------------------------------------------------------------------------- #

outputs:
  home: [ 'html', 'rss', 'openSearch', 'manifest', 'search', 'turbo' ]
  page: [ 'html', 'json' ]

# -------------------------------------------------------------------------------------------------------------------- #
# Sitemap.
# -------------------------------------------------------------------------------------------------------------------- #

sitemap:
  changefreq: 'weekly'
  priority: 0.5

# -------------------------------------------------------------------------------------------------------------------- #
# Taxonomies.
# -------------------------------------------------------------------------------------------------------------------- #

taxonomies:
  tag: 'tags'
  category: 'categories'
  author: 'authors'

# -------------------------------------------------------------------------------------------------------------------- #
# Permalinks.
# -------------------------------------------------------------------------------------------------------------------- #

permalinks:
  drafts: '/:section/:year/:month/:slug/'

# -------------------------------------------------------------------------------------------------------------------- #
# Markup.
# -------------------------------------------------------------------------------------------------------------------- #

markup:
  highlight:
    codeFences: true
    noClasses: false
  tableOfContents:
    endLevel: 4
    startLevel: 2

# -------------------------------------------------------------------------------------------------------------------- #
# Minify.
# -------------------------------------------------------------------------------------------------------------------- #

minify:
  minifyOutput: true
  tdewolff:
    html:
      keepWhitespace: false

# -------------------------------------------------------------------------------------------------------------------- #
# Languages.
# -------------------------------------------------------------------------------------------------------------------- #

languages:
  ru:
    title: 'Library Online'
    contentDir: 'content/ru'
    languageName: 'Русский'
    languageCode: 'ru-RU'
    weight: 10
    params:
      description: 'Заметки на тему администрирования и разработки различных систем, приложений и серверов.'
      languageLang: 'ru'
  en:
    title: 'Library Online'
    contentDir: 'content/en'
    languageName: 'English'
    languageCode: 'en-US'
    weight: 20
    params:
      description: 'Notes on system administration and development of various systems, applications and servers.'
      languageLang: 'en'
