# -------------------------------------------------------------------------------------------------------------------- #
# GENERAL
# -------------------------------------------------------------------------------------------------------------------- #

baseURL: 'https://lib.onl/'
theme: [ 'ui-shortcode', 'ui-custom', 'ui-blog' ]
DefaultContentLanguage: 'ru'
defaultContentLanguageInSubdir: true
disableHugoGeneratorInject: true
pagination:
  pagerSize: 20
pygmentsUseClasses: true
pygmentsCodeFences: true
publishDir: 'public'
enableRobotsTXT: true
rssLimit: 50

# -------------------------------------------------------------------------------------------------------------------- #
# ERRORS
# -------------------------------------------------------------------------------------------------------------------- #

ignoreErrors:
  - 'error-remote-getjson'

# -------------------------------------------------------------------------------------------------------------------- #
# MEDIA TYPES
# -------------------------------------------------------------------------------------------------------------------- #

mediaTypes:
  'application/opensearchdescription+xml':
    suffixes: [ 'xml' ]
  'text/plain':
    suffixes: [ 'txt', 'ps1', 'bat', 'cmd', 'ini', 'cfg', 'sh' ]

# -------------------------------------------------------------------------------------------------------------------- #
# OUTPUT FORMATS
# -------------------------------------------------------------------------------------------------------------------- #

outputFormats:
  openSearch:
    baseName: 'opensearch'
    mediaType: 'application/opensearchdescription+xml'
    rel: 'search'
    notAlternative: true
  manifest:
    baseName: 'manifest'
    mediaType: 'application/json'
    rel: 'manifest'
    notAlternative: true
  search:
    baseName: 'search'
    mediaType: 'application/json'
    isPlainText: true
    notAlternative: true
  turbo:
    baseName: 'turbo'
    mediaType: 'application/rss+xml'
    notAlternative: true

# -------------------------------------------------------------------------------------------------------------------- #
# OUTPUTS
# -------------------------------------------------------------------------------------------------------------------- #

outputs:
  home: [ 'html', 'rss', 'openSearch', 'manifest', 'search', 'turbo' ]
  page: [ 'html', 'json' ]

# -------------------------------------------------------------------------------------------------------------------- #
# SITEMAP
# -------------------------------------------------------------------------------------------------------------------- #

sitemap:
  changefreq: 'weekly'
  priority: 0.5

# -------------------------------------------------------------------------------------------------------------------- #
# TAXONOMIES
# -------------------------------------------------------------------------------------------------------------------- #

taxonomies:
  tag: 'tags'
  category: 'categories'
  author: 'authors'

# -------------------------------------------------------------------------------------------------------------------- #
# PERMALINKS
# -------------------------------------------------------------------------------------------------------------------- #

permalinks:
  articles: '/:year/:month/:slug/'
  drafts: '/:year/:month/:slug/'
  faq: '/:year/:month/:slug/'

# -------------------------------------------------------------------------------------------------------------------- #
# MARKUP
# -------------------------------------------------------------------------------------------------------------------- #

markup:
  highlight:
    codeFences: true
    noClasses: false
    lineNos: true
  tableOfContents:
    endLevel: 4
    startLevel: 2

# -------------------------------------------------------------------------------------------------------------------- #
# MINIFY
# -------------------------------------------------------------------------------------------------------------------- #

minify:
  minifyOutput: true

# -------------------------------------------------------------------------------------------------------------------- #
# LANGUAGES
# -------------------------------------------------------------------------------------------------------------------- #

languages:
  ru:
    title: 'Library Online'
    contentDir: 'content/ru'
    languageName: 'Русский'
    languageCode: 'ru-RU'
    weight: 10
    params:
      description: 'Заметки на тему администрирования и разработки различных систем, приложений и серверов.'
      languageLang: 'ru'
  en:
    title: 'Library Online'
    contentDir: 'content/en'
    languageName: 'English'
    languageCode: 'en-US'
    weight: 20
    params:
      description: 'Notes on system administration and development of various systems, applications and servers.'
      languageLang: 'en'
