# ----------------------------------------------------------------------------------------------------------------------
# Russian.
# ----------------------------------------------------------------------------------------------------------------------

[ru]
title = 'Library Online'
description = 'Заметки на тему администрирования и разработки различных систем, приложений и серверов.'
contentDir = 'content/ru'
languageName = 'Русский'
languageCode = 'ru-RU'
languageLang = 'ru'
weight = 10

# ----------------------------------------------------------------------------------------------------------------------
# English.
# ----------------------------------------------------------------------------------------------------------------------

[en]
title = 'Library Online'
description = 'Notes on system administration and development of various systems, applications and servers.'
contentDir = 'content/en'
languageName = 'English'
languageCode = 'en-US'
languageLang = 'en'
weight = 20
