# ----------------------------------------------------------------------------------------------------------------------
# Blog.
# ----------------------------------------------------------------------------------------------------------------------

[[main]]
name = 'Статьи'
pre = 'fas fa-book'
url = '/ru/posts/'
identifier = 'blog'
weight = 10

# ----------------------------------------------------------------------------------------------------------------------
# Meta.
# ----------------------------------------------------------------------------------------------------------------------

[[main]]
name = 'META'
pre = 'fas fa-list'
identifier = 'meta'
weight = 999

[[main]]
name = 'Авторы'
pre = 'fas fa-user-circle'
url = '/ru/authors/'
identifier = 'authors'
weight = 10
parent = 'meta'

[[main]]
name = 'Категории'
pre = 'fas fa-folder-open'
url = '/ru/categories/'
identifier = 'categories'
weight = 20
parent = 'meta'

[[main]]
name = 'Теги'
pre = 'fas fa-tags'
url = '/ru/tags/'
identifier = 'tags'
weight = 30
parent = 'meta'

[[main]]
name = 'Архив'
pre = 'fas fa-archive'
url = '/ru/archive/'
identifier = 'archive'
weight = 100
parent = 'meta'

# ----------------------------------------------------------------------------------------------------------------------
# Donate.
# ----------------------------------------------------------------------------------------------------------------------

[[main]]
name = 'Поддержать'
pre = 'fas fa-gift'
url = '/ru/donate/'
identifier = 'donate'
weight = 9910

# ----------------------------------------------------------------------------------------------------------------------
# About.
# ----------------------------------------------------------------------------------------------------------------------

[[main]]
name = 'О проекте'
pre = 'fas fa-info-circle'
url = '/ru/about/'
identifier = 'about'
weight = 9999
