# ----------------------------------------------------------------------------------------------------------------------
# Blog.
# ----------------------------------------------------------------------------------------------------------------------

[[main]]
name = 'Articles'
pre = 'fas fa-book'
url = '/en/posts/'
identifier = 'blog'
weight = 10

# ----------------------------------------------------------------------------------------------------------------------
# Meta.
# ----------------------------------------------------------------------------------------------------------------------

[[main]]
name = 'META'
pre = 'fas fa-list'
identifier = 'meta'
weight = 999

[[main]]
name = 'Authors'
pre = 'fas fa-user-circle'
url = '/en/authors/'
identifier = 'authors'
weight = 10
parent = 'meta'

[[main]]
name = 'Categories'
pre = 'fas fa-folder-open'
url = '/en/categories/'
identifier = 'categories'
weight = 20
parent = 'meta'

[[main]]
name = 'Tags'
pre = 'fas fa-tags'
url = '/en/tags/'
identifier = 'tags'
weight = 30
parent = 'meta'

[[main]]
name = 'Archive'
pre = 'fas fa-archive'
url = '/en/archive/'
identifier = 'archive'
weight = 100
parent = 'meta'

# ----------------------------------------------------------------------------------------------------------------------
# Donate.
# ----------------------------------------------------------------------------------------------------------------------

[[main]]
name = 'Donate'
pre = 'fas fa-gift'
url = '/en/donate/'
identifier = 'donate'
weight = 9910

# ----------------------------------------------------------------------------------------------------------------------
# About.
# ----------------------------------------------------------------------------------------------------------------------

[[main]]
name = 'About'
pre = 'fas fa-info-circle'
url = '/en/about/'
identifier = 'about'
weight = 9999
