# ----------------------------------------------------------------------------------------------------------------------
# General.
# ----------------------------------------------------------------------------------------------------------------------

images = ['img/og.png']
categories = ['news', 'education', 'security', 'utilities']

[sections]
blog = ['posts']

# ----------------------------------------------------------------------------------------------------------------------
# Comments
# ----------------------------------------------------------------------------------------------------------------------

[comments.utterances]
repo = 'site-0001/comments'
issue_term = ''
theme = 'github-light'

# ----------------------------------------------------------------------------------------------------------------------
# Contacts.
# ----------------------------------------------------------------------------------------------------------------------

[contacts]
name = 'Library Online'
email = 'mail@lib.onl'
twitter = ''
vk = ''
youtube = ''

# ----------------------------------------------------------------------------------------------------------------------
# License & Developer information.
# ----------------------------------------------------------------------------------------------------------------------

[license]
name = 'CC BY-SA 4.0'
url = 'https://creativecommons.org/licenses/by-sa/4.0/'

[developer]
name = 'Library Online'
url = 'https://lib.onl/'

# ----------------------------------------------------------------------------------------------------------------------
# Organization.
# ----------------------------------------------------------------------------------------------------------------------

[organization]
name = 'Library Online'
legalName = 'Library Online'
foundingDate = '2019'
description = ''
url = 'https://lib.onl/'
email = 'mail@lib.onl'
telephone = ''
contactType = 'customer service'

[organization.logo]
url = 'img/og.png'
height = '630'
width = '1200'

[organization.address]
street = ''
locality = ''
region = ''
postalCode = ''
country = ''

[organization.social]
url = [
  'https://twitch.tv/',
  'https://twitter.com/',
  'https://vk.com/'
]
