# -------------------------------------------------------------------------------------------------------------------- #
# CONTENT
# -------------------------------------------------------------------------------------------------------------------- #

home:
  sections: [ 'articles' ]

content:
  sections: [ 'articles', 'faq' ]

archive:
  sections: [ 'articles' ]

# -------------------------------------------------------------------------------------------------------------------- #
# META
# -------------------------------------------------------------------------------------------------------------------- #

manifest:
  short_name:
    en: 'Lib.Onl'
    ru: 'Lib.Onl'
  color:
    background: '#f8f9fa'
    theme: '#f8f9fa'
  categories:
    - 'books'
    - 'education'
    - 'utilities'

ui:
  color:
    theme:
      light: '#f8f9fa'
      dark: ''

# -------------------------------------------------------------------------------------------------------------------- #
# SEO
# -------------------------------------------------------------------------------------------------------------------- #

author:
  name: 'Kai Kimera'
  email: 'mail@lib.onl'

images:
  - 'favicon-512.png'

organization:
  logo: 'img/logo.min.svg'
  address:
    city: 'Moscow'
    region: 'Moscow Region'
    country: 'Russia'
  contacts:
    type: 'customer service'
    email: 'mail@lib.onl'
    telephone: '+7 (000) 000-0000'
  foundingDate: '2020'
  sameAs:
    - ''

# -------------------------------------------------------------------------------------------------------------------- #
# API
# -------------------------------------------------------------------------------------------------------------------- #

api:
  user_agent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36'
  github:
    url: 'https://api.github.com'
    user: 'ghapibot'
    email: ''
    token: ''
  gitlab:
    url: 'https://gitlab.com/api/v4'
    user: 'glapibot'
    email: ''
    token: ''

# -------------------------------------------------------------------------------------------------------------------- #
# BREADCRUMB
# -------------------------------------------------------------------------------------------------------------------- #

breadcrumb:
  divider: '/'

# -------------------------------------------------------------------------------------------------------------------- #
# SEARCH
# -------------------------------------------------------------------------------------------------------------------- #

search:
  internal:
    enabled: true
    sections: [ 'articles', 'faq', 'resources' ]
  bing:
    enabled: false
  google:
    enabled: true
  yandex:
    enabled: true

# -------------------------------------------------------------------------------------------------------------------- #
# TAXONOMY
# -------------------------------------------------------------------------------------------------------------------- #

taxonomy:
  authors:
    grid:
      cols: 2
    cover:
      size: '128px'
      avatar:
        size: '196'
  categories:
    grid:
      cols: 2
    cover:
      size: '96px'
      icon:
        name: 'far fa-folder-open'
        size: '2x'
  list:
    cover:
      size: '96px'
      icon:
        name: 'far fa-file-lines'
        size: '2x'

# -------------------------------------------------------------------------------------------------------------------- #
# NODE
# -------------------------------------------------------------------------------------------------------------------- #

node:
  cover:
    enabled: true
    image:
      placeholder: 'https://images.unsplash.com/photo-1585776245991-cf89dd7fc73a'
      crop: 'edges'
      fit: 'crop'
    lg:
      width: '1600'
      height: '900'
    md:
      width: '160'
      height: '160'
  tabs:
    source:
      enabled: false
    changelog:
      enabled: true
    info:
      enabled: true
      categories:
        enabled: true
      tags:
        enabled: true
      authors:
        enabled: true
      related:
        enabled: true
      meta:
        enabled: true
      stats:
        enabled: true
    comments:
      enabled: true
      giscus:
        repo: 's8956/comments'
        repo_id: 'R_kgDOKgu0Tg'
        category: 'Site'
        category_id: 'DIC_kwDOKgu0Ts4CaJ2z'
        mapping: 'pathname'
        strict: '1'
        reactions: '1'
        metadata: '0'
        position: 'top'
        theme: 'preferred_color_scheme'
    share:
      enabled: true
      social:
        enabled: true
      qrcode:
        enabled: true
      url:
        enabled: true
      file:
        enabled: true
