# -------------------------------------------------------------------------------------------------------------------- #
# Meta.
# -------------------------------------------------------------------------------------------------------------------- #

author:
  name: 'Kitsune Solar'
  email: 'mail@lib.onl'

manifest:
  short_name: 'Lib.Onl'
  color:
    background: '#f8f9fa'
    theme: '#f8f9fa'
  categories:
    - 'books'
    - 'education'
    - 'utilities'

ui:
  color:
    theme:
      light: '#f8f9fa'
      dark: ''

# -------------------------------------------------------------------------------------------------------------------- #
# API.
# -------------------------------------------------------------------------------------------------------------------- #

api:
  user_agent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36'
  github:
    token: 'Z2hwX3dReDZ3OVpTRjVIejlENUQ3ck9JV0hOOGVxU3NDRjQxUzF3Zw=='

# -------------------------------------------------------------------------------------------------------------------- #
# Search.
# -------------------------------------------------------------------------------------------------------------------- #

search:
  bing:
    enabled: false
  google:
    enabled: true
  yandex:
    enabled: false

# -------------------------------------------------------------------------------------------------------------------- #
# Taxonomy.
# -------------------------------------------------------------------------------------------------------------------- #

taxonomy:
  authors:
    grid:
      cols: 2
    cover:
      size: '120px'
      avatar:
        size: '256'
  categories:
    grid:
      cols: 3
    cover:
      size: '96px'
      icon:
        name: 'far fa-folder-open'
        size: '2x'

# -------------------------------------------------------------------------------------------------------------------- #
# Node.
# -------------------------------------------------------------------------------------------------------------------- #

node:
  cover:
    image:
      enabled: true
      placeholder: 'https://images.unsplash.com/photo-1585776245991-cf89dd7fc73a'
      crop: 'entropy'
      fit: 'crop'
      lg:
        width: '1600'
        height: '900'
      md:
        width: '160'
        height: '160'
  tabs:
    info:
      enabled: true
      categories:
        enabled: true
      tags:
        enabled: true
      authors:
        enabled: true
      related:
        enabled: true
      meta:
        enabled: true
      stats:
        enabled: true
    license:
      enabled: true
    comments:
      enabled: true
      giscus:
        repo: 'site-0003/comments'
        repo_id: 'R_kgDOKaWVNA'
        category: 'Site'
        category_id: 'DIC_kwDOKaWVNM4CZwyI'
        mapping: 'pathname'
        strict: '1'
        reactions: '1'
        metadata: '0'
        position: 'top'
        theme: 'preferred_color_scheme'
    share:
      enabled: true
      social:
        enabled: true
      qrcode:
        enabled: true
      url:
        enabled: true
      file:
        enabled: true
