image: hugomods/hugo:exts-0.145.0

variables:
  GIT_STRATEGY: clone
  GIT_SUBMODULE_STRATEGY: recursive
  GIT_SUBMODULE_UPDATE_FLAGS: --remote --jobs 4
  HUGO_ENV: 'mirror.01'

pages:
  script:
    - hugo
  artifacts:
    paths:
      - public
    expire_in: 1 week
  only:
    - main
