image: registry.gitlab.com/pages/hugo/hugo_extended:latest

variables:
  GIT_STRATEGY: clone
  GIT_SUBMODULE_STRATEGY: recursive
  GIT_SUBMODULE_UPDATE_FLAGS: --remote --jobs 4
  HUGO_ENV: 'libit.ru'

pages:
  script:
    - hugo
  artifacts:
    paths:
      - public
    expire_in: 1 week
  only:
    - main
