# -------------------------------------------------------------------------------------------------------------------- #
# General.
# -------------------------------------------------------------------------------------------------------------------- #

baseURL: 'https://lib.onl/'

languages:
  ru:
    title: 'Library Online'
