# -------------------------------------------------------------------------------------------------------------------- #
# General.
# -------------------------------------------------------------------------------------------------------------------- #

baseURL: 'https://libit.ru/'

languages:
  ru:
    title: 'Library IT'
  en:
    title: 'Library IT'
