# -------------------------------------------------------------------------------------------------------------------- #
# Meta.
# -------------------------------------------------------------------------------------------------------------------- #

manifest:
  short_name:
    en: 'Lib IT'
    ru: 'Lib IT'
