# -------------------------------------------------------------------------------------------------------------------- #
# Meta.
# -------------------------------------------------------------------------------------------------------------------- #

manifest:
  short_name:
    en: 'Example.Com'
    ru: 'Example.Com'
