# -------------------------------------------------------------------------------------------------------------------- #
# General.
# -------------------------------------------------------------------------------------------------------------------- #

baseURL: 'https://example.com/'

languages:
  ru:
    title: 'Example.Com'
