name: 'GitHub Pages'

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 */4 * * *'

env:
  OWNER: '${{ github.repository_owner }}'
  HUGO_ENV: ''
  HUGO_HOST: 'lib.onl'

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: 'DEPLOY'
    permissions:
      contents: 'write'
    concurrency:
      group: '${{ github.workflow }}-${{ github.ref }}'
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
          fetch-depth: 0
      - name: 'Checkout submodules'
        run: git submodule update --recursive --remote --merge
      - name: 'Setup Hugo'
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.146.2'
          extended: true
      - name: 'Build'
        run: hugo --environment '${{ env.HUGO_ENV }}'
      - name: 'Deploy'
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          personal_token: '${{ secrets.BOT_PAGES_TOKEN }}'
          external_repository: '${{ env.OWNER }}/${{ env.OWNER }}.github.io'
          publish_branch: 'main'
          publish_dir: 'public'
          cname: '${{ env.HUGO_HOST }}'
          user_name: '${{ secrets.BOT_PAGES_NAME }}'
          user_email: '${{ secrets.BOT_PAGES_EMAIL }}'
